// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgvwidupxkvxsvugnohf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBndndpZHVweGt2eHN2dWdub2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODM0MjUsImV4cCI6MjA2MTE1OTQyNX0.ltudYC-4wByekqwK5fZ6hhbGQrWH2SBjQmf5tXCaI8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);